on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
env:
      DB_DATABASE: cakephp
      DB_USER: root
      DB_PASSWORD: root
jobs:
  testsuite:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.2', '7.4']
        db-type: [mysql]
        include:
          - php-version: '7.2'
            db-type: 'mysql'
        
    steps:
    - uses: actions/checkout@v2
 
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, intl, apcu, memcached, redis, pdo_${{ matrix.db-type }}
        ini-values: apc.enable_cli = 1
        coverage: pcov
        
    - name: Set up MySQL
      run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
          
    - name: config stuffs
      run: |
            echo "require_once 'vendors/autoload.php';" >> app/Config/bootstrap.php
            cp app/Config/database.php.default app/Config/database.php
      
      
    - name: Composer install
      run: | 
          composer install --ignore-platform-req=ext-mcrypt
          composer update --ignore-platform-req=ext-mcrypt
          cd app
          composer install --ignore-platform-req=ext-mcrypt
          composer update --ignore-platform-req=ext-mcrypt
    
       
    - name: Run PHPUnit
      run: |     
       chmod +x app/Console/cake  
       app/Console/cake test app All --stderr --verbose
